import type { ReactNode } from 'react'
import type {
  ArchiveCenterEntry,
  AutoTaskBoardItem,
  PublishCenterEntry,
  TemplatePoolEntry,
} from './DashboardAutoTaskPanel'

type TaskCardTone = 'running' | 'queue' | 'paused' | 'done'

type TaskCardRenderer = (item: AutoTaskBoardItem, tone: TaskCardTone, index: number) => ReactNode

type ParentTaskView = {
  id: string
  title: string
  template: string
  childCount: number
  progress: number
  blockedPoint: string
  domains: Array<string | undefined>
}

type TaskGroupView = {
  id: string
  label: string
  template: string
  domain: string
  projectLine: string
  count: number
}

type RiskSummary = {
  predictedHigh: number
  needHuman: number
  blocked: number
  externalBlocked: number
  leadTransferred: number
}

type DomainLoadSummaryEntry = {
  domain: string
  total: number
  running: number
  queued: number
  needHuman: number
  blocked: number
}

type ConsultantSummaryEntry = {
  consultantId: string
  owner: string
  activeLoad: number
  converted: number
  total: number
  conversionRate: number
}

type ReassignmentRecord = {
  lead_id?: string
  reassigned_at?: string
  task_name: string
  consultant_id?: string
  reassigned_to?: string
  reassigned_reason?: string
}

type RecentDecision = {
  taskName: string
  agent: string
  decision: string
  reason: string
  detail: string
  timestamp: string
}

type RecentResult = {
  task_name: string
  updated_at?: string
  result: {
    content: string
  }
}

type PoolTab = {
  key: 'builder' | 'media' | 'family' | 'business' | 'personal'
  label: string
  max_concurrency: number
  running_count: number
  queue_count: number
  health: 'healthy' | 'warning' | 'critical'
}

type ExecutionStatusSummary = {
  running: number
  queued: number
  blocked: number
  needHuman: number
}

type ArchiveStructureGroup = {
  structureId: string
  count: number
  topAccount?: [string, number]
}

function getRecommendedTemplates(
  templates: TemplatePoolEntry[],
  domain: string,
  assetType: PublishCenterEntry['assetType'],
) {
  const expectedAssetType =
    assetType === 'media'
      ? 'script'
      : assetType === 'business'
        ? 'reply'
        : assetType === 'family'
          ? 'plan'
          : 'generic'

  return templates
    .filter((template) => template.domain === domain && template.asset_type === expectedAssetType)
    .sort((a, b) => {
      if (b.use_count !== a.use_count) return b.use_count - a.use_count
      return new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime()
    })
    .slice(0, 2)
}

export function AutoTaskOperationsView({
  parentTaskViews,
  taskGroups,
  todayAutoGeneratedCount,
  riskSummary,
  loading,
  domainLoadSummary,
  humanPendingTasks,
  consultantSummary,
  reassignmentRecords,
}: {
  parentTaskViews: ParentTaskView[]
  taskGroups: TaskGroupView[]
  todayAutoGeneratedCount: number
  riskSummary: RiskSummary
  loading: boolean
  domainLoadSummary: DomainLoadSummaryEntry[]
  humanPendingTasks: AutoTaskBoardItem[]
  consultantSummary: ConsultantSummaryEntry[]
  reassignmentRecords: ReassignmentRecord[]
}) {
  return (
    <>
      <section className="scheduler-overview-card">
        <div className="scheduler-section-title">主任务 / 场景任务组进度</div>
        {parentTaskViews.length ? (
          <div className="scheduler-parent-task-list">
            {parentTaskViews.slice(0, 6).map((parent) => (
              <article className="scheduler-parent-task-card" key={parent.id}>
                <div className="scheduler-parent-task-top">
                  <strong>{parent.title}</strong>
                  <span>{parent.template}</span>
                </div>
                <div className="scheduler-parent-task-meta">
                  <span>子任务 {parent.childCount}</span>
                  <span>进度 {parent.progress}%</span>
                  <span>阻塞点 {parent.blockedPoint}</span>
                </div>
                <div className="scheduler-parent-task-domains">
                  {parent.domains.map((domain) => (
                    <span key={`${parent.id}-${domain}`} className="scheduler-parent-domain-chip">{domain}</span>
                  ))}
                </div>
              </article>
            ))}
          </div>
        ) : <div className="auto-task-empty">暂无主任务进度</div>}
        {taskGroups.length ? (
          <div className="scheduler-task-groups">
            {taskGroups.slice(0, 6).map((group) => (
              <div className="scheduler-task-group-chip" key={group.id}>
                <strong>{group.label}</strong>
                <span>{group.template} · {group.count} tasks · {group.domain} / {group.projectLine}</span>
              </div>
            ))}
          </div>
        ) : null}
      </section>

      <section className="scheduler-overview-card">
        <div className="scheduler-section-title">运营摘要</div>
        <div className="scheduler-overview-grid scheduler-overview-grid-ops">
          <div className="scheduler-overview-metric"><span>今日 auto_generated</span><strong>{todayAutoGeneratedCount}</strong></div>
          <div className="scheduler-overview-metric is-warning"><span>predicted_risk</span><strong>{riskSummary.predictedHigh}</strong></div>
          <div className="scheduler-overview-metric is-warning"><span>need_human</span><strong>{riskSummary.needHuman}</strong></div>
          <div className="scheduler-overview-metric is-failed"><span>blocked</span><strong>{riskSummary.blocked}</strong></div>
          <div className="scheduler-overview-metric is-warning"><span>external_blocked</span><strong>{riskSummary.externalBlocked}</strong></div>
          <div className="scheduler-overview-metric"><span>lead_transferred</span><strong>{riskSummary.leadTransferred}</strong></div>
          <div className="scheduler-overview-metric is-concurrency"><span>同步状态</span><strong>{loading ? '刷新中' : '已同步'}</strong></div>
        </div>
        <div className="scheduler-summary-grid">
          <div className="scheduler-decisions-card">
            <div className="scheduler-section-title">各 domain 负载摘要</div>
            <div className="scheduler-decision-list">
              {domainLoadSummary.length ? domainLoadSummary.map((entry) => (
                <article className="scheduler-decision-item" key={entry.domain}>
                  <div className="scheduler-decision-top"><strong>{entry.domain}</strong><span>{entry.total} tasks</span></div>
                  <p>running {entry.running} · queued {entry.queued}</p>
                  <small>blocked {entry.blocked} · need_human {entry.needHuman}</small>
                </article>
              )) : <div className="auto-task-empty">暂无 domain 负载数据</div>}
            </div>
          </div>
          <section className="scheduler-decisions-card scheduler-pending-human-card">
            <div className="scheduler-section-title">待人工处理摘要</div>
            <div className="scheduler-decision-list">
              {humanPendingTasks.length ? humanPendingTasks.slice(0, 8).map((item, index) => {
                const latestDecision = [...(item.decision_log ?? [])].slice(-1)[0]
                return (
                  <article className="scheduler-decision-item scheduler-human-item" key={`${item.task_name}-ops-human-${index}`}>
                    <div className="scheduler-decision-top"><strong>{item.task_name}</strong><span>{item.domain ?? '-'}</span></div>
                    <p>{latestDecision?.reason ?? 'need_human'}</p>
                    <small>{item.human_owner ?? '-'} · {latestDecision?.detail ?? item.manual_decision ?? '-'}</small>
                  </article>
                )
              }) : <div className="auto-task-empty">暂无待人工处理任务</div>}
            </div>
          </section>
        </div>
        <div className="scheduler-summary-grid">
          <section className="scheduler-decisions-card">
            <div className="scheduler-section-title">顾问负载 / 转化率</div>
            <div className="scheduler-decision-list">
              {consultantSummary.length ? consultantSummary.map((entry) => (
                <article className="scheduler-decision-item" key={entry.consultantId}>
                  <div className="scheduler-decision-top"><strong>{entry.owner}</strong><span>{entry.consultantId}</span></div>
                  <p>active_load {entry.activeLoad} · total {entry.total}</p>
                  <small>conversion_rate {entry.conversionRate}%</small>
                </article>
              )) : <div className="auto-task-empty">暂无顾问负载数据</div>}
            </div>
          </section>
          <section className="scheduler-decisions-card">
            <div className="scheduler-section-title">改派记录</div>
            <div className="scheduler-decision-list">
              {reassignmentRecords.length ? reassignmentRecords.map((item) => (
                <article className="scheduler-decision-item" key={`${item.lead_id}-${item.reassigned_at}`}>
                  <div className="scheduler-decision-top"><strong>{item.task_name}</strong><span>{item.reassigned_at ?? '-'}</span></div>
                  <p>{item.consultant_id ?? '-'} → {item.reassigned_to ?? '-'}</p>
                  <small>{item.reassigned_reason ?? '-'}</small>
                </article>
              )) : <div className="auto-task-empty">暂无改派记录</div>}
            </div>
          </section>
        </div>
      </section>
    </>
  )
}

export function AutoTaskExecutionView({
  poolTabs,
  normalizedActivePool,
  onSelectPool,
  executionStatusSummary,
  runningTasks,
  queuedTasks,
  blockedPoolTasks,
  needHumanPoolTasks,
  renderTaskCard,
  recentDecisions,
  recentResults,
  publishSourceGroups,
  templatePool,
  controlLoadingTask,
  onManualControlTask,
  archiveContentLineGroups,
  archiveAccountLineGroups,
  archiveStructureGroups,
  archiveDomainGroups,
  onMarkTemplateSource,
}: {
  poolTabs: PoolTab[]
  normalizedActivePool: PoolTab['key']
  onSelectPool: (poolKey: PoolTab['key']) => void
  executionStatusSummary: ExecutionStatusSummary
  runningTasks: AutoTaskBoardItem[]
  queuedTasks: AutoTaskBoardItem[]
  blockedPoolTasks: AutoTaskBoardItem[]
  needHumanPoolTasks: AutoTaskBoardItem[]
  renderTaskCard: TaskCardRenderer
  recentDecisions: RecentDecision[]
  recentResults: RecentResult[]
  publishSourceGroups: Array<[string, PublishCenterEntry[]]>
  templatePool: TemplatePoolEntry[]
  controlLoadingTask: string
  onManualControlTask: (taskName: string, action: 'mark_manual_published') => void
  archiveContentLineGroups: Array<[string, ArchiveCenterEntry[]]>
  archiveAccountLineGroups: Array<[string, ArchiveCenterEntry[]]>
  archiveStructureGroups: ArchiveStructureGroup[]
  archiveDomainGroups: Array<[string, ArchiveCenterEntry[]]>
  onMarkTemplateSource: (taskName: string) => void
}) {
  return (
    <>
      <section className="scheduler-overview-card">
        <div className="scheduler-section-title">当前实例池任务</div>
        <div className="scheduler-pool-overview">
          {poolTabs.map((pool) => (
            <button
              key={pool.key}
              type="button"
              className={`scheduler-pool-card ${normalizedActivePool === pool.key ? 'is-active' : ''} is-${pool.health}`}
              onClick={() => onSelectPool(pool.key)}
            >
              <div className="scheduler-pool-card-top"><strong>{pool.label}</strong><span>{pool.health}</span></div>
              <div className="scheduler-pool-card-metrics"><span>并发 {pool.running_count}/{pool.max_concurrency}</span><span>queue {pool.queue_count}</span></div>
            </button>
          ))}
        </div>
        <div className="scheduler-overview-grid">
          <div className="scheduler-overview-metric is-concurrency"><span>running</span><strong>{executionStatusSummary.running}</strong></div>
          <div className="scheduler-overview-metric"><span>queued</span><strong>{executionStatusSummary.queued}</strong></div>
          <div className="scheduler-overview-metric is-failed"><span>blocked</span><strong>{executionStatusSummary.blocked}</strong></div>
          <div className="scheduler-overview-metric is-warning"><span>need_human</span><strong>{executionStatusSummary.needHuman}</strong></div>
          <div className="scheduler-overview-metric"><span>pool</span><strong>{normalizedActivePool}</strong></div>
        </div>
      </section>

      <section className="scheduler-queue-card">
        <div className="scheduler-section-title">调度队列 · {normalizedActivePool}</div>
        <div className="scheduler-queue-grid">
          <div className="scheduler-lane">
            <div className="scheduler-lane-head"><h4>Running</h4><span>{runningTasks.length}</span></div>
            <div className="scheduler-lane-list">{runningTasks.length ? runningTasks.map((item, index) => renderTaskCard(item, 'running', index)) : <div className="auto-task-empty">暂无 Running 任务</div>}</div>
          </div>
          <div className="scheduler-lane">
            <div className="scheduler-lane-head"><h4>Queued</h4><span>{queuedTasks.length}</span></div>
            <div className="scheduler-lane-list">{queuedTasks.length ? queuedTasks.map((item, index) => renderTaskCard(item, 'queue', index)) : <div className="auto-task-empty">暂无 Queued 任务</div>}</div>
          </div>
          <div className="scheduler-lane">
            <div className="scheduler-lane-head"><h4>Blocked</h4><span>{executionStatusSummary.blocked}</span></div>
            <div className="scheduler-lane-list">{blockedPoolTasks.length ? blockedPoolTasks.map((item, index) => renderTaskCard(item, 'paused', index)) : <div className="auto-task-empty">暂无 Blocked 任务</div>}</div>
          </div>
          <div className="scheduler-lane">
            <div className="scheduler-lane-head"><h4>Need Human</h4><span>{executionStatusSummary.needHuman}</span></div>
            <div className="scheduler-lane-list">{needHumanPoolTasks.length ? needHumanPoolTasks.map((item, index) => renderTaskCard(item, 'done', index)) : <div className="auto-task-empty">暂无 Need Human 任务</div>}</div>
          </div>
        </div>
      </section>

      <div className="scheduler-summary-grid">
        <section className="scheduler-decisions-card">
          <div className="scheduler-section-title">最近决策</div>
          <div className="scheduler-decision-list">
            {recentDecisions.length ? recentDecisions.map((decision, index) => (
              <article className="scheduler-decision-item" key={`${decision.taskName}-${decision.timestamp}-${index}`}>
                <div className="scheduler-decision-top"><strong>{decision.decision}</strong><span>{decision.timestamp}</span></div>
                <p>{decision.taskName} · {decision.agent}</p>
                <small>{decision.reason} · {decision.detail}</small>
              </article>
            )) : <div className="auto-task-empty">暂无自动决策记录</div>}
          </div>
        </section>
        <section className="scheduler-alert-card">
          <div className="scheduler-section-title">当前执行结果</div>
          <div className="scheduler-alert-group">
            {recentResults.length ? recentResults.map((entry, index) => (
              <div className="scheduler-result-item" key={`${entry.task_name}-execution-${index}`}>
                <strong>{entry.task_name}</strong>
                <p>{entry.result.content}</p>
                <small>{entry.updated_at ?? '-'}</small>
              </div>
            )) : <div className="auto-task-empty">暂无结果</div>}
          </div>
        </section>
      </div>

      <div className="scheduler-summary-grid scheduler-centers-grid">
        <section className="scheduler-alert-card">
          <div className="scheduler-section-title">发布中心</div>
          <div className="scheduler-alert-group">
            {publishSourceGroups.length ? publishSourceGroups.map(([sourceKey, entries], groupIndex) => (
              <section className="scheduler-archive-group" key={`${sourceKey}-${groupIndex}`}>
                <div className="scheduler-archive-group-head">
                  <strong>{sourceKey}</strong>
                  <span>{entries.length} 个版本</span>
                </div>
                <div className="scheduler-alert-group">
                  {entries.map((entry, index) => {
                    const recommendedTemplates = getRecommendedTemplates(templatePool, entry.domain, entry.assetType)
                    return (
                      <article className="scheduler-result-item scheduler-center-card" key={`${entry.taskName}-publish-${index}`}>
                        <div className="scheduler-center-card-top">
                          <strong>{entry.taskName}</strong>
                          <span>{entry.domain} · {entry.assetType} · {entry.contentVariant || '-'}</span>
                        </div>
                        <div className="scheduler-publish-grid">
                          <div><span>brand_display</span><p>{entry.brandDisplay || entry.brandLine || '-'}</p></div>
                          <div><span>mcn_display</span><p>{entry.mcnDisplay || '-'}</p></div>
                          <div><span>account_display</span><p>{entry.accountDisplay || entry.accountLine || '-'}</p></div>
                          <div><span>account_type</span><p>{entry.accountType || '-'}</p></div>
                          <div><span>tier</span><p>{entry.tier || '-'}</p></div>
                          <div><span>route_result</span><p>{entry.routeResult || '-'}</p></div>
                          <div><span>route_target</span><p>{entry.routeTarget || '-'}</p></div>
                          <div><span>can_close_deal</span><p>{typeof entry.canCloseDeal === 'boolean' ? String(entry.canCloseDeal) : '-'}</p></div>
                          <div><span>distribution_channel</span><p>{entry.distributionChannel || '-'}</p></div>
                          <div><span>content_variant</span><p>{entry.contentVariant || '-'}</p></div>
                          <div><span>source_line</span><p>{entry.sourceLine || '-'}</p></div>
                          <div><span>persona</span><p>{entry.result.persona || entry.result.persona_id || '-'}</p></div>
                          <div><span>structure_type</span><p>{entry.result.structure_type || '-'}</p></div>
                          <div><span>structure_id</span><p>{entry.result.structure_id || '-'}</p></div>
                          <div><span>CTA policy</span><p>{entry.result.cta_policy || '-'}</p></div>
                          <div><span>骨架摘要</span><p>{entry.result.structure_summary || Object.keys(entry.result.section_map || {}).join(' / ') || '-'}</p></div>
                          <div><span>source_type</span><p>{entry.source?.source_type || '-'}</p></div>
                          <div><span>source_project</span><p>{entry.source?.source_project || '-'}</p></div>
                          <div><span>role_version</span><p>{entry.roleVersion || '-'}</p></div>
                          <div><span>章节标题</span><p>{entry.source?.chapter_title || '-'}</p></div>
                          <div><span>推荐发布时间</span><p>{entry.result.recommend_publish_time || '-'}</p></div>
                          <div><span>发布频率</span><p>{entry.result.recommend_frequency || '-'}</p></div>
                          <div><span>今日建议发</span><p>{typeof entry.result.publish_today === 'boolean' ? (entry.result.publish_today ? 'true' : 'false') : '-'}</p></div>
                          <div><span>建议标题</span><p>{entry.result.suggested_title || entry.result.title || '-'}</p></div>
                          <div><span>首评建议</span><p>{entry.result.suggested_first_comment || '-'}</p></div>
                          <div><span>互动问题</span><p>{entry.result.suggested_interaction_question || '-'}</p></div>
                          <div><span>风控提示</span><p>{entry.result.publish_risk_warning?.join(' / ') || '无'}</p></div>
                        </div>
                        {entry.assetType === 'media' ? (
                          <div className="scheduler-publish-grid">
                            <div><span>title</span><p>{entry.result.title || '-'}</p></div>
                            <div><span>hook</span><p>{entry.result.hook || '-'}</p></div>
                            <div><span>outline</span><p>{entry.result.outline?.join(' / ') || '-'}</p></div>
                            <div><span>script</span><p>{entry.result.script || '-'}</p></div>
                            <div><span>publish_text</span><p>{entry.result.publish_text || '-'}</p></div>
                          </div>
                        ) : null}
                        {entry.contentVariant === 'article' ? (
                          <div className="scheduler-publish-grid">
                            <div><span>structure</span><p>{entry.result.structure?.join(' / ') || entry.result.outline?.join(' / ') || '-'}</p></div>
                            <div><span>section_map</span><p>{Object.entries(entry.result.section_map || {}).map(([key, value]) => `${key}: ${value}`).join(' / ') || '-'}</p></div>
                            <div><span>full_article</span><p>{entry.result.full_article || entry.result.script || '-'}</p></div>
                          </div>
                        ) : null}
                        {entry.assetType === 'business' ? (
                          <div className="scheduler-publish-grid">
                            <div><span>摘要</span><p>{entry.result.content || entry.result.title || '-'}</p></div>
                            <div><span>跟进建议</span><p>{entry.result.publish_text || entry.result.hook || '-'}</p></div>
                          </div>
                        ) : null}
                        {entry.assetType === 'family' ? (
                          <div className="scheduler-publish-grid">
                            <div><span>学习计划</span><p>{entry.result.outline?.join(' / ') || entry.result.content || '-'}</p></div>
                            <div><span>提醒文案</span><p>{entry.result.publish_text || entry.result.hook || '-'}</p></div>
                          </div>
                        ) : null}
                        {entry.assetType === 'generic' ? (
                          <div className="scheduler-publish-grid">
                            <div><span>摘要</span><p>{entry.result.content || '-'}</p></div>
                          </div>
                        ) : null}
                        <div className="scheduler-center-actions">
                          <button className="auto-task-row-btn" type="button" onClick={async () => { await navigator.clipboard.writeText(entry.result.publish_text || entry.result.content || '') }}>
                            复制可发布内容
                          </button>
                          <button className="auto-task-row-btn" type="button" onClick={() => onManualControlTask(entry.taskName, 'mark_manual_published')}>
                            {controlLoadingTask === `${entry.taskName}:mark_manual_published` ? '记录中...' : '人工已发布'}
                          </button>
                          <small>{entry.updatedAt ?? '-'}</small>
                        </div>
                        {entry.result.manual_published_at ? <small>已由 {entry.result.manual_published_by || '-'} 于 {entry.result.manual_published_at} 记录人工发布</small> : null}
                        <div className="scheduler-template-recommendations">
                          <span>推荐相似模板</span>
                          {recommendedTemplates.length ? recommendedTemplates.map((template) => (
                            <div className="scheduler-template-rec-item" key={template.template_id}>
                              <strong>{template.source_task_name ?? template.template_id}</strong>
                              <small>use_count {template.use_count}</small>
                            </div>
                          )) : <small>暂无</small>}
                        </div>
                      </article>
                    )
                  })}
                </div>
              </section>
            )) : <div className="auto-task-empty">暂无可发布结果</div>}
          </div>
        </section>

        <section className="scheduler-alert-card">
          <div className="scheduler-section-title">结果沉淀中心</div>
          <div className="scheduler-task-groups">
            {archiveContentLineGroups.map(([line, entries]) => <div className="scheduler-task-group-chip" key={`content-${line}`}><strong>content_line</strong><span>{line} · {entries.length} 条</span></div>)}
            {archiveAccountLineGroups.map(([line, entries]) => <div className="scheduler-task-group-chip" key={`account-${line}`}><strong>account_display</strong><span>{entries[0]?.accountDisplay || line} · {entries.length} 条</span></div>)}
          </div>
          <div className="scheduler-task-groups">
            {archiveStructureGroups.map((entry) => (
              <div className="scheduler-task-group-chip" key={`structure-${entry.structureId}`}>
                <strong>structure_id</strong>
                <span>{entry.structureId} · use_count {entry.count} · top_account {entry.topAccount?.[0] || '-'} ({entry.topAccount?.[1] || 0})</span>
              </div>
            ))}
          </div>
          <div className="scheduler-archive-groups">
            {archiveDomainGroups.length ? archiveDomainGroups.map(([domain, entries]) => (
              <section className="scheduler-archive-group" key={domain}>
                <div className="scheduler-archive-group-head">
                  <strong>{domain}</strong>
                  <span>{entries.length} 条</span>
                </div>
                <div className="scheduler-alert-group">
                  {entries.map((entry, index) => {
                    const recommendedTemplates = getRecommendedTemplates(templatePool, domain, entry.assetType)
                    return (
                      <article className="scheduler-result-item scheduler-center-card" key={`${entry.taskName}-archive-${index}`}>
                        <div className="scheduler-center-card-top">
                          <strong>{entry.taskName}</strong>
                          <span>{entry.assetType} · {entry.contentVariant || '-'}</span>
                        </div>
                        <div className="scheduler-publish-grid">
                          <div><span>brand_display</span><p>{entry.brandDisplay || entry.brandLine || '-'}</p></div>
                          <div><span>mcn_display</span><p>{entry.mcnDisplay || '-'}</p></div>
                          <div><span>account_display</span><p>{entry.accountDisplay || entry.accountLine || '-'}</p></div>
                          <div><span>account_type</span><p>{entry.accountType || '-'}</p></div>
                          <div><span>tier</span><p>{entry.tier || '-'}</p></div>
                          <div><span>route_result</span><p>{entry.routeResult || '-'}</p></div>
                          <div><span>route_target</span><p>{entry.routeTarget || '-'}</p></div>
                          <div><span>can_close_deal</span><p>{typeof entry.canCloseDeal === 'boolean' ? String(entry.canCloseDeal) : '-'}</p></div>
                          <div><span>distribution_channel</span><p>{entry.distributionChannel || '-'}</p></div>
                          <div><span>content_variant</span><p>{entry.contentVariant || '-'}</p></div>
                          <div><span>source_line</span><p>{entry.sourceLine || '-'}</p></div>
                          <div><span>persona</span><p>{entry.result.persona || entry.result.persona_id || '-'}</p></div>
                          <div><span>structure_type</span><p>{entry.result.structure_type || '-'}</p></div>
                          <div><span>structure_id</span><p>{entry.result.structure_id || '-'}</p></div>
                          <div><span>CTA policy</span><p>{entry.result.cta_policy || '-'}</p></div>
                          <div><span>骨架摘要</span><p>{entry.result.structure_summary || Object.keys(entry.result.section_map || {}).join(' / ') || '-'}</p></div>
                          <div><span>source_type</span><p>{entry.source?.source_type || '-'}</p></div>
                          <div><span>source_project</span><p>{entry.source?.source_project || '-'}</p></div>
                          <div><span>role_version</span><p>{entry.roleVersion || '-'}</p></div>
                          <div><span>章节标题</span><p>{entry.source?.chapter_title || '-'}</p></div>
                        </div>
                        <p>{entry.result.content || entry.result.publish_text || '-'}</p>
                        <div className="scheduler-center-actions">
                          <button className="auto-task-row-btn" type="button" onClick={async () => { await navigator.clipboard.writeText(JSON.stringify(entry.result, null, 2)) }}>
                            复制
                          </button>
                          <button className="auto-task-row-btn" type="button" onClick={() => onMarkTemplateSource(entry.taskName)}>
                            {controlLoadingTask === `${entry.taskName}:mark_template_source` ? '标记中...' : '标记为模板来源'}
                          </button>
                          <small>{entry.updatedAt ?? '-'}</small>
                        </div>
                        <div className="scheduler-template-recommendations">
                          <span>推荐相似模板</span>
                          {recommendedTemplates.length ? recommendedTemplates.map((template) => (
                            <div className="scheduler-template-rec-item" key={template.template_id}>
                              <strong>{template.source_task_name ?? template.template_id}</strong>
                              <small>use_count {template.use_count}</small>
                            </div>
                          )) : <small>暂无</small>}
                        </div>
                      </article>
                    )
                  })}
                </div>
              </section>
            )) : <div className="auto-task-empty">暂无可沉淀结果</div>}
          </div>
        </section>
      </div>
    </>
  )
}
